apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
  namespace: go
  labels:
    app: p2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p2
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
      - name: p2
        image: p2:1.0
        ports:
        - containerPort: 8080
