apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1
  namespace: go
  labels:
    app: p1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p1
  template:
    metadata:
      labels:
        app: p1
    spec:
      containers:
      - name: p1
        image: p1:1.0
        ports:
        - containerPort: 8080
