# ---- Build stage ----
FROM golang:1.22.2 AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# ---- Run stage ----
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

# Optional: include static files if used
COPY static ./static

EXPOSE 8080

CMD ["./main"]
